language: php
sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

services:
  - memcached

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  # set low version, so deps can be installed on 5.3
  - composer config platform.php 5.4
  - composer update --no-interaction --prefer-source

script:
  - composer validate
  - phpunit

# vim:ts=2:sw=2:et
